### ISSUE TITLE
Cannot sign repository without sudo -i

### ISSUE THREAD

**Issue by ADepic** [Skyfleet/sky-update#2]
Running the "curl" command in sudo does not work.
You need to do the `sudo -i` command to go to root (because `su` doesn't work) and the run the curl command normally.

This problem happens on my raspberry pi, linux mint and lubuntu computer.

**Comment by 0pcom** [comment]
only the second part of the command (`apt-key-add`) needs root or sudo

**Comment by ADepic** [comment]
```curl -L http://skyfleet.github.io/sky-update/KEY.asc | sudo apt-key add -```

Works, but again the fact that sudo needs to be in the second part isn't made clear

**Comment by ADepic** [comment]
Has been made clear, thanks
