### ISSUE TITLE
Detailed and clear guide for raspberry PIs

### ISSUE THREAD

**Issue by ADepic** [Skyfleet/sky-update#3]
I created a guide for raspberry PIs here:
https://github.com/ADepic/SkywirePiMainnet/blob/master/README.md

I think it would be helpful to link my guide saying that it is for raspberry PIs only (that is if you think my guide is correct).

Currently it is focused around GNU/Linux (and probably mac) users, and so it doesn't cover the use of putty for windows. 

It also outlines in detail how to set up your PIs for easy SSH access and how to get some important pieces of information (such as gateway IP address), so my guide may be useful for creating similar guides for different hardware

**Comment by 0pcom** [comment]
Hey that's some very nice work. I don't typically endorse guides but I'm glad you included my package repository in this guide.

asxtree has images for rpi now which are based on raspbian. If you ask me, a lot of the manual steps which you list are best scripted into the image configuration so people don't get confused.

I will link your guide but please be sure to update it as the names of scripts have changed. Currently there is a method which is being worked out to avoid the need for skyimager.

skywire-startup has changed to skybian-firstrun.

It would be best if, at the point of the repo configuration, you linked to here: https://skyfleet.github.io/sky-update

so when things change there you aren't having to make updates

**Comment by ADepic** [comment]
Wait, so do you have to do 
```
systemctl enable skybian-firstrun

systemctl start skybian-firstrun
```

**Comment by ADepic** [comment]
I don't exactly know how to update this section of my guide now:
> If any of that didn't work, then Look if any bugs showed up in the terminal. You can copy and paste that error message and submit it as an issue in this repository, or you can ask the skycoin telegram. DO NOT POST THE ENTIRE OUTPUT IN YOUR TERMINAL, IS THIS CONTAINS YOUR SECRET KEYS. Instead you want to paste the code after --END SKYCONF LOGS-- to make sure no one sees your secret keys.

Since the new `skybian-firstrun` command works differently, I don't know where the private keys are pasted when you run the command.

**Comment by ADepic** [comment]
seems like since a service is directly run, that is not a problem anymore

**Comment by 0pcom** [comment]
skybian-firstrun relies on the configuration written to the boot sector by skyimager, and also I think skyimager creates the needed config.json files in the images

**Comment by ADepic** [comment]
My guide no longer contains `skybian-firstrun`, but rather follows the manual configuration steps.
